version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/spring-boot-validator-0.0.1-SNAPSHORT.jar
  discard-paths: yes