version: 0.2

phases:
  build:
    commands:
      - echo Running test cases...
      - mvn test
      - echo Entered the build phase...
      - mvn clean install
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - "**/*"
  discard-paths: yes